[package]
name = "vector"
version = "0.1.0"
authors = ["maik <maikklein@googlemail.com>"]

[dependencies]
typenum = "1.3.1"
generic-array = "0.3.1"
num = "0.1"
rand = "0.3"
arrayvec = "0.3.16"
lazy_static = "0.2.1"
[dependencies.coroutine]
git = "https://github.com/MaikKlein/coroutine-rs.git"
